# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ice}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nate Kidwell"]
  s.date = %q{2010-06-04}
  s.description = %q{User templates written in javascript}
  s.email = %q{nate@ludicast.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     ".specification",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "ice.gemspec",
     "ice_js/History.md",
     "ice_js/Readme.md",
     "ice_js/lib/path_helper.js",
     "ice_js/spec/commands/example_command.rb",
     "ice_js/spec/dom.html",
     "ice_js/spec/node.js",
     "ice_js/spec/rhino.js",
     "ice_js/spec/server.html",
     "ice_js/spec/server.rb",
     "ice_js/spec/unit/spec.helper.js",
     "ice_js/spec/unit/spec.js",
     "init.rb",
     "lib/extras/ice_view.rb",
     "lib/ice.rb",
     "lib/ice/base_cube.rb",
     "lib/ice/cube_association.rb",
     "lib/ice/cubeable.rb",
     "lib/parser.js",
     "lib/routes_js.rb",
     "rails/init.rb",
     "spec/base_cube_spec.rb",
     "spec/cube_spec.rb",
     "spec/ice_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ludicast/ice}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{User templates written in javascript}
  s.test_files = [
    "spec/base_cube_spec.rb",
     "spec/cube_spec.rb",
     "spec/ice_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<therubyracer>, ["= 0.7.1"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.2.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<therubyracer>, ["= 0.7.1"])
      s.add_dependency(%q<activesupport>, [">= 2.2.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<therubyracer>, ["= 0.7.1"])
    s.add_dependency(%q<activesupport>, [">= 2.2.0"])
  end
end

